### ISSUE TITLE
IP Address Invalid Format Issue

### ISSUE THREAD

**Issue by Ilikemining1** [RattletraPM/gbaxxdumper#3]
When you type an IP Address, you have to type it with a port number after, or else it gives you an invalid format error.  It claims the IP address is <address>:port:port even though it connects.

**Comment by RattletraPM** [comment]
I tried but I honestly couldn't replicate this, you can see on the demo I linked too it worked with a regular internal IP address (192.168.120.16) without using any workarounds. Is the IP you're using public or, if not, could you write it here to let me try and replicate it myself?

**Comment by Ilikemining1** [comment]
Okay, I've figured out what the issue really seems to be.  With your 192.*.*.* ip address, the first part is 3 characters long.  My internal addresses are 10.*.*.*.  I just tried again, and typing 10.1.0.233 doesn't work, while padding it with a 0, so 010.1.0.233 connects without an issue.  I think the port number was just padding out the number of characters?

Edit: Just looked at the code, the issue would appear to be the `length < 11` part of the code, as my ip is 10 characters long without the padding 0.

Also, how long should a dump take?  When I did get it working, it was really slow, I gave up after over an hour to dump Pokemon LeafGreen.

**Comment by RattletraPM** [comment]
Yeah, I was suspecting it being that part - seems like I left it there when I was testing stuff out as I pushed whatever code I had at on the drive at release time tbh. I'll fix it right away and push a hotfix.

As for dumping speed, it takes a while but it seems to vary from server software to server software really, it might be related to ftplib being old but I honestly don't know =/

(EDIT: Didn't mean to close this just yet lol)

**Comment by RattletraPM** [comment]
That should fix it. Hopefully I didn't mess anything up this time.
