### ISSUE TITLE
I did not create dspatch-gui

### ISSUE THREAD

**Issue by retroheim** [RattletraPM/gbaxxdumper#4]
If you read my readme, I have not created the dspatch-gui, bennyman123abc did. I am just adding upon and optimizing it, and most importantly, adding customizability so that you can modify the Download Station ROM's appearance.

Sorry for the trouble!

Sincerely,
RetroHeim.

**Comment by RattletraPM** [comment]
My bad, thanks for letting me know! Fixed it right away!

**Comment by retroheim** [comment]
no problem!
